language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ryan1007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=True ryan1007/react-test npm test

after_success:
  - docker build -t ryan1007/multi-client ./client
  - docker build -t ryan1007/multi-nginx ./nginx
  - docker build -t ryan1007/multi-server ./server
  - docker build -t ryan1007/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ryan1007/multi-client
  - docker push ryan1007/multi-nginx
  - docker push ryan1007/multi-server
  - docker push ryan1007/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-590421022552
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
